### ISSUE TITLE
ios Build fails when adding geofence 

### ISSUE THREAD

**Issue by josiareubro** [cowbell/cordova-plugin-geofence#100]
Hi ,

   While adding the geofence plugin , my application build fails for ios .But working on android .
The geo fence version I  included is <gap:plugin name="cordova-plugin-geofence" source="npm" version="0.4.2"/> . 
ios build shows error  **Oh geez. Your build failed. Sorry, but a problem occurred on the build server** .

Please help in solving this issue...
Thanks in advance .

**Comment by tsubik** [comment]
This kind of error doesn't tell anything. Please if you are not sure that the problem is with the plugin itself, please try to ask on StackOverflow first.
