### ISSUE TITLE
Build Fails for Android

### ISSUE THREAD

**Issue by DataHerder** [cowbell/cordova-plugin-geofence#101]
This is the error I'm getting:

Hi guys, getting an error only for your plugin from Android:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-location:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I've isolated with building only android platform and only with geofence plugin so I know this plugin is the offending one.  Below is a very recent link I found in regards to this issue:  https://software.intel.com/en-us/forums/intel-xdk/topic/595059

Please let me know if I'm missing something here or another plugin to include for this.  Geofence is a big part of the app but not so critical that it we could wait for it's inclusion in the final release.  I can confirm this plugin works well for the latest version of iOS.  I guess I could split the application into 2, including it in the iOS build and not including this in the android build.  Please advise if this error can be fixed in a timely manner.

Thank you!

**Comment by tsubik** [comment]
Hey, looks like you don't have any google play services location installed. Plugin uses the newest version of play services, of course you can change it before build in `platforms/android/project.properties` file. Check if you have anything in folder `ANDROID_SDK/extras/google/m2repository/com/google/android/gms/play-services-location`

**Comment by DataHerder** [comment]
Confirmed!  Builds on Android and iOS.
