### ISSUE TITLE
PhoneGap Build - Error "Multiple dex files define..." with Official PGB Push Notification Plugin

### ISSUE THREAD

**Issue by fsciuti** [cowbell/cordova-plugin-geofence#102]
Hi, I have an error on Android building. The error is:  
*com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;*

The problem may be like this:
[https://github.com/phonegap-build/PushPlugin/issues/492](https://github.com/phonegap-build/PushPlugin/issues/492)
[https://github.com/Wizcorp/phonegap-facebook-plugin/issues/992](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/992)

It's possible to solve in PGB? Can you help me?
I have attached *Build Log* and *config.xml*.

Thank you!

[Android_Build_Log.txt](https://github.com/cowbell/cordova-plugin-geofence/files/34155/Android_Build_Log.txt)

[config.xml.txt](https://github.com/cowbell/cordova-plugin-geofence/files/34156/config.xml.txt)

**Comment by tsubik** [comment]
I have no idea what could be wrong, but this seems to be not the plugin related itself. Maybe StackOverflow would be a better place for this issue. Please reopen if it not solved and comment if you found the answer.
