### ISSUE TITLE
Applications using the same plugin

### ISSUE THREAD

**Issue by DataHerder** [cowbell/cordova-plugin-geofence#103]
Is it possible that if 2 or more applications are using the same plugin, geofences will be pooled into each application and each application will display notifications from all the apps?

The reason why I ask this is is because it's happening to 2 applications I have on my phone that are running this plugin.  I realize that it could be because of "localStorage" variable which is easy but I just want to make sure that when using this plugin it will not interfere with notification from another application using this plugin.  Can you confirm this has been tested?

Thank you!

**Comment by tsubik** [comment]
Geofences are stored and handled always per application. I have 2 apps using this plugin installed and everything work as it should be.

**Comment by DataHerder** [comment]
Ok thanks!  Just making sure before I send this application to the store.  Thank you!  "Anything that can go wrong, will go wrong." - Murphy's Law
