### ISSUE TITLE
[IOS] The plugin works on IOS8 but not on IOS7

### ISSUE THREAD

**Issue by Zorkham** [cowbell/cordova-plugin-geofence#104]
Hi, I have XCODE (v7.1) I create a Cordova (v5.3.3) project, adding the IOS platform and install the plugin "cordova-plugin-geofence" (v0.5.0).

When I test on IOS 8 & IOS 9 simulator and IOS 9 device, the geofence works!

But I have an error when I running the same on my IOS 7 Device (IPHONE 4) :

<pre>-[UIApplication currentUserNotificationSettings]: unrecognized selector sent to instance 0x1653f680
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication currentUserNotificationSettings]: unrecognized selector sent to instance 0x1653f680'</pre>

The error make reference to this line in the "GeofencePlugin.swift" file (on the checkRequirements()) :

<pre>if let notificationSettings = UIApplication.sharedApplication().currentUserNotificationSettings() {</pre>

If I have correctly understand the problem, it's cause before the IOS 8 version, it was another way to make this statement "currentUserNotificationSettings".

Thanks in advance,

Zorkham.

**Comment by tsubik** [comment]
I hope that works. I wasn't able to test it on iOS 7, but it should :smile:
