### ISSUE TITLE
Android: Working on mobile devices but not a tablet device

### ISSUE THREAD

**Issue by derek1988ec** [cowbell/cordova-plugin-geofence#105]
Hello All,

Wanted to ask, I'm trying to use geofence for android. In the mobile device it looks fine but it doesn't work on the tablet device.

I'm using Nexus 7 and Samsung Galaxy Tab S for the tablet and used Samsung Galaxy S6 and Motorola Nexus 6 for mobile devices

I checked through window.geofence.getWatched() method and found that the geofences are stored for both tablet and phone, but the phone triggers it and not the tablet. Any idea why?

Many thanks in advance for the help!

**Comment by tsubik** [comment]
Is there anything in the logs? Geofences are stored internally in SQLite database but it looks like geofencing API doesn't work if it so, there should be a message in the device logs.

**Comment by tsubik** [comment]
Closed due to inactivity.
