### ISSUE TITLE
Notifications happening multiple times when in fence

### ISSUE THREAD

**Issue by Tempus35** [cowbell/cordova-plugin-geofence#108]
So I have a sample fence set up to send a notification on enter and exit of the fence. It works but I noticed that leaving the app running in the background and staying in the area marked as the fence that the notification comes up again and again at random times. Is there a way to stop this, I would like it to work only on leaving or entering, not while in the fence.

**Comment by tsubik** [comment]
What radius do you have? Basically, this plugin is a wrapper around native android and iOS so there is not so much to do with its accuracy.

**Comment by Tempus35** [comment]
I believe I have it set for 500 meters. Some quick questions: Is the plugin using the geolocation plugin and do I need to set it up for high accuracy? If not, do you have it set for high accuracy or a way to set it? Is there some option or options to tell it to not redo a notification if a timer is still active? Is it possible to make an event that will stop a firing of another notification if the person has entered the fence but not left it yet?

**Comment by tsubik** [comment]
It doesn't use geolocation API. It basically mimics native Geofencing API http://developer.android.com/training/location/geofencing.html. If from some reasons API is not so accurate for you then it could detect that you actually left the fence. Do you have wifi on? Some say that pulling GPS location helps for accuracy issues. I've never tried that personally, though.

**Comment by Tempus35** [comment]
Thanks for that link, so two questions based on the information there. Is there a way to set your plugin to use GEOFENCE_TRANSITION_DWELL which seems it would help some of the "alert spam". Does it also use INSIDE_LOW_CONFIDENCE or OUTSIDE_LOW_CONFIDENCE to stop notifications?

It is ok if it does not, it was likely the wifi thing, thought it used GPS, that is causing the issue. Also thanks for the plugin, it is very useful.

**Comment by tsubik** [comment]
Unfortunately, setting DWELL is currently not possible. But feel free to fork and submit pull request for that :+1:

**Comment by Tempus35** [comment]
Alright, I might do that at some point, I think I will close this for now. Your plugin is doing great at what it was made for, I just need to add some tweaks to my system to make it work the way I want.
