### ISSUE TITLE
Not sure what to edit

### ISSUE THREAD

**Issue by nursyafiah** [cowbell/cordova-plugin-geofence#109]
Hi, I have installed the plugin to my project successfully. Now, i am stuck as to where or which files should I edit? For example, I am aware that you'll need to change the latitude and longitude so that the notification appear when  you are in the correct place. So, which files should I change?

Thank you for taking your time reading and replying to my email.

**Comment by nursyafiah** [comment]
Oh yah, I also realized that LocalStorage (JAVA file) has codes related to database. Hence, do I need to create a database?

**Comment by tsubik** [comment]
Yeah I just took some shortcut there after experimenting with webview LocalStorage. I decided to not change an interface of data persistence and I store data in Sqllite database. I'm not quite sure I understand your question, though. Why you want to change anything in Java native code?

**Comment by nursyafiah** [comment]
@tsubik i need to state the latitude and longitude values based on the place where i want the notification to appear right?

**Comment by tsubik** [comment]
This is not a bug or feature request so I suggest to post this question on stackoverflow. I want to keep this place for actual bugs.
