### ISSUE TITLE
How to detect transition when transitionType is set for TransitionType.BOTH

### ISSUE THREAD

**Issue by coddypotter** [cowbell/cordova-plugin-geofence#112]
I've added a geo fence and set transitionType to TransitionType.BOTH. how to identify this in window.geofence.onTransitionReceived function?

**Comment by tsubik** [comment]
If you're using notification just add initial transitionType to `data` object. If not, you can look for transitionType in geofence list fetched by `getWatched` function as you have `id` of geofence.
