### ISSUE TITLE
iOS 9.2 no notifications

### ISSUE THREAD

**Issue by slowsword** [cowbell/cordova-plugin-geofence#114]
When using simulated locations on an iPod Touch i get this in the console:

    GeofencePlugin - Entering region 01
    GeofencePlugin - Creating notification
    GeofencePlugin - didReceiveTransition
    GeofencePlugin - State for region 01
    GeofencePlugin - didReceiveLocalNotification

But no notification is displayed on the device.

     window.geofence.addOrUpdate({
                             id:             "01",
                             latitude:       51.5085300,	//26.383315,
                             longitude:      -0.1257400, //-80.099635,
                             radius:         100000,
                             transitionType: 3, //TransitionType.ENTER,
                             notification: {
                             id:             1,
                             title:          "Welcome to the office",
                             text:           "You just arrived at our new office.",
                             openAppOnClick: true
                             }
                             }).then(function () {
                                     console.log('Geofence successfully added');
                                     }, function (reason) {
                                     console.log('Adding geofence failed', reason);
                                     });

Any help is much appreciated

**Comment by slowsword** [comment]
Please disregard this and mark it as complete. It works for me on 9.2. Did not realize notification was only when the app is not open....

**Comment by sunojvijayan** [comment]
Can you please check this I am not getting any notification on device.

https://github.com/cowbell/cordova-plugin-geofence/issues/110

**Comment by tsubik** [comment]
Actually, notification shows when app is either open or close.
