### ISSUE TITLE
Build fails on cordova-ios 4.0.x

### ISSUE THREAD

**Issue by jeanbaptistevilain** [cowbell/cordova-plugin-geofence#117]
Hi,

Thanks for the work on the plugin. I cannot seem to compile a Cordova project using the 0.5.0 version of the plugin though, as it fails in Xcode with :
`GeofencePlugin.swift:149:20: Value of type 'UIView' has no member 'stringByEvaluatingJavaScriptFromString'`

My environment : 
cordova 6.0.0
cordova-ios 4.0.1
cordova-plugin-geofence 0.5.0
Xcode 7.2

I'm no cordova plugin expert but from what I've seen the webView type in CDVPlugin was updated in cordova-ios 4.0, changing from UIWebView to UIView in order to support WkWebView as well.

Hope this helps

**Comment by nwidal** [comment]
+1

**Comment by johnrobertcobbold** [comment]
I shopped around for what other people are doing as my knowledge is quite limited and started hacking this @ https://github.com/cowbell/cordova-plugin-geofence/pull/120
At least it builds :)

Perhaps someone with more knowledge can take it from here ?

**Comment by tsubik** [comment]
Should be resolved by 2a55abb9.

**Comment by johnrobertcobbold** [comment]
@tsubik it's working nicely, thanks for that
