### ISSUE TITLE
Error in new iOS code for JS function

### ISSUE THREAD

**Issue by Tempus35** [cowbell/cordova-plugin-geofence#122]
As the title says, there is a code error in the executeJS function for the new iOS code, I have tried fixing it but apparently I do not know swift2 very well.

**Comment by jlamim** [comment]
Anyone have the solution?

**Comment by Tempus35** [comment]
Not yet, I have been working on figuring it out

**Comment by Tempus35** [comment]
I changed my function to: (It gives warnings but seems to work for me, likely needs someone else to update it better)

````
func evaluateJs (script: String) {
        if webView != nil {
            if let uiWebView = webView! as? UIWebView {
                uiWebView.stringByEvaluatingJavaScriptFromString(script)
            } else if let wkWebView = webView as? WKWebView {
                wkWebView.evaluateJavaScript(script, completionHandler: nil)
            }
        } else {
            log("webView is null")
        }
    }
````

**Comment by johnrobertcobbold** [comment]
@Tempus35 Are you using Cordova IOS 4 and therefore maybe wkWebView ? If so, I can confirm that things are working. If you are using uiWebView, I do not know then but I am sure someone else can feedback,

**Comment by Tempus35** [comment]
I have ios 3.9.2 it seems

**Comment by johnrobertcobbold** [comment]
`cordova platforms ls` will let you know which version you are using for ios.
If it is < 4, you are definitively using uiWebView.

Not the answer to your problem, but wkWebView brings a nice speed improvement, you can consider upgrading (just make sure you either plugins have been upgraded by their authors to be compatible with it)

**Comment by Tempus35** [comment]
Yes I am less than 4 but at the time this app is on crunch time and being it is working fine except for some slight issues with geofencing on iOS I am not going to try to upgrade yet.

**Comment by johnrobertcobbold** [comment]
@Tempus35, for reasons explained here https://github.com/cowbell/cordova-plugin-geofence/issues/127, I had to stop using wkWebView and went back to uiView. I can now confirm your bug and the fix you mentioned above.

**Comment by Tempus35** [comment]
@johnrobertcobbold Good to know
