### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by gaecer** [cowbell/cordova-plugin-geofence#132]
XCode Version 7.2.1 (7C1002)
simulator or device (iOS 8.4, 9.2)
Working on Android but on iOS I don't get any notifications!

Geofence successfully initialized
Geofence successfully added (just one because I know the limit of 20)
Starting monitoring for region CLCircularRegion ..
radius enough (50000 where the lat and lng are my current position)

**Comment by antonino-tocco** [comment]
Hi gaecer, the plugin notify the enter/exit on a region. If you are yet in the location no notification are show.

**Comment by Buddikazz** [comment]
not woring on ios with giving radius 30000m

**Comment by brijesh-p** [comment]
@gaecer - pls let me know the root cause of issue, having same at my end. Thanks

**Comment by gaecer** [comment]
@brijesh-p I don't remember exactly now, but I think I did my own native function at the end, because this plugin is just not working well.
