### ISSUE TITLE
compile failure: "_OBJC_CLASS_$_WKWebView"

### ISSUE THREAD

**Issue by ghost** [cowbell/cordova-plugin-geofence#146]
Simply adding this plugin causes archiving to fail in Xcode.  My project is currently on the latest cordova(6.1.1) and cordova-ios(4.1.1).  Plugin version: 0.6.0.

I have found that commenting out these two lines allows the project to build and function normally:
https://github.com/cowbell/cordova-plugin-geofence/blob/master/src/ios/GeofencePlugin.swift#L173-L174

Full error in Xcode:
  "_OBJC_CLASS_$_WKWebView", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed and Exploded> of District_Dogs.GeofencePlugin.evaluateJs (Swift.String) -> () in GeofencePlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by paulosaure** [comment]
Go to your Project -> General -> Linked Frameworks and Libraries then add WebKit.framework

GL && HF

**Comment by tsubik** [comment]
This PR #164 may have resolved this problem as well. I'm closing now, please reopen if the problem still occurs.
