### ISSUE TITLE
The more I use it, the less sense this library make

### ISSUE THREAD

**Issue by ThaBrad** [cowbell/cordova-plugin-geofence#151]
Now after finding out the problem with overlapping GeoFences, the next big thing is there.

When I test it (iOS Simulator) and I go, let's say from London to Austria (near the geopoint), the event triggers.

BUT… when I do the same, but have a **gpx-track** (Xcode, which works perfectly fine, running from point A --> B, as I can see running maps next to my app) **NOTHING**!!!

**Comment by tsubik** [comment]
This is only wrapper on native geofence API. The problem is with iOS Simulator not the plugin itself.
