### ISSUE TITLE
Start geofencing without user action

### ISSUE THREAD

**Issue by igordisco** [cowbell/cordova-plugin-geofence#154]
Hi,

I am developing an medical appointment app and due to the high rate of fraud I would like to know if there is a way to track if the patient showed up at the appointment.

Something like pointing the lat-long of the medical center and if the user gets inside the fencing range, we get a confirmation.

Is there a way of doing this without notifying the user? Is that allowed? And if it is, how do we omit this information?

**Comment by tsubik** [comment]
Hey @igordisco I think this question is more suitable for stackoverflow as you ask about many general ideas. Using this plugin you could write some native code to send request to your server, take a look [here](https://github.com/cowbell/cordova-plugin-geofence#listening-for-geofence-transitions-in-native-code).

**Comment by tsubik** [comment]
You could also take a look at some forks of this plugin. I'm totally sure some folks had the similar problem that you have.
