### ISSUE TITLE
promises stay pending on android

### ISSUE THREAD

**Issue by cutout33** [cowbell/cordova-plugin-geofence#155]
Hi,

I wrote a small application using this plugin, it seems to work on iOS but not on android. it does not return the promises value for any of the methods. can someone help me please?

**Comment by davjand** [comment]
I'm having the same issue but just a thought - do you have google play services enabled on your device?

**Comment by davjand** [comment]
I think this issue is caused by the plugin being unable to connect to Google Play services.

I've debugged the java code and find that the onConnectionFailed method on AbstractGoogleServiceCommand.java is being called.

It is a bug in the sense that promise should reject in this situation.

A fix might be to ensure that your device or emulator has up to date google play services installed

**Comment by cutout33** [comment]
am testing on real devices, and yes it has google play services enabled. any way to work around this issue??

**Comment by cutout33** [comment]
I enabled the logs, the only msg am getting 'geofence intent created' snd still the promises are pending! no errors, play services is latest and same code is working on iOS!

**Comment by davjand** [comment]
The only thing I can think of to do is to debug the geofence code in
android studio and see where it's messing up. I don't know if you're
familiar with it but I found it quite easy for the first time - just open
the platforms/android folder after you've done a build and then you can
debug from there

**Comment by cutout33** [comment]
OK, I think it is related to the play services not being up to date but I don't really know how to fix it! this is the error I get in android studio:

> The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 8298000 but found 6171000.  You must have the following declaration within the <application> element:     < meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

the tag is already the file and on the phones I test on the version of google play services is 2.9.56 (it is latest)
 can you please help me figure this out?

**Comment by cutout33** [comment]
I finally figured this out! I had to change the version number inside cordova/plugins/com.google.playservices/version.xml and then remove and add android via cordova...

Thanks for the help
