### ISSUE TITLE
notificationData.name when multiple notifications exist on device

### ISSUE THREAD

**Issue by YairHadari** [cowbell/cordova-plugin-geofence#156]
Thanks for contributing the plugin to the community.
It is working as expected!!!!

I have one issue with the plugin.
The user is moving between the defined geofences and getting notification for each geofence he entered (as expected).
The user is not clicking the notifications nor opening the application.
All notification are shown on the device (the notifications in not overriding each other).
When the user is open one of the notifications he got, the notificationData.name of each notification is the same (of the last geofence sent the notification).

Is there an option that each notification will save it's notificationData.name?
Or
The notifications will override the previous notification?

Thanks again
Yair

**Comment by tsubik** [comment]
Fixed id #206
