### ISSUE TITLE
Build on iOS failed

### ISSUE THREAD

**Issue by PaperMonster** [cowbell/cordova-plugin-geofence#16]
Hi, I've been trying to build my Cordova (+Ionic) project using this plugin on Android and iOS. Building and running on Android went smoothly, but failed on iOS. Here is what I've done so far:

1) Add the plugin using `cordova plugin add https://github.com/cowbell/cordova-plugin-geofence`
2) Add iOS platform `ionic platform add ios`
3) Run on iOS simulator
````
ionic emulate ios
````
The error occured:

        Check dependencies
        Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').
        
        ** BUILD FAILED **
        
        
        The following build commands failed:
        	Check dependencies
        (1 failure)
        Error: /Users/rasita.sa/Documents/myPhonegap/myProject/platforms/ios/cordova/run: Command failed with exit code 65
            at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
            at ChildProcess.emit (events.js:98:17)
            at maybeClose (child_process.js:756:16)
            at Process.ChildProcess._handle.onexit (child_process.js:823:5)

 4) Open the Xcode project in platforms/ios and change the project's and target's iOS Deployment Target from 6.0 to 7.0. After hitting Run button I found another error:
![screen shot 2015-01-28 at 12 09 33 pm](https://cloud.githubusercontent.com/assets/10735822/5932746/8fcbfb8a-a6e6-11e4-9f47-c484ced8c30e.png)

I also try adding and building iOS platform in the sample application, got the same result.

Cordova version: 3.6.3-0.2.13
Ionic version: 1.0.0-beta.13

Did I do something wrong?

**Comment by tsubik** [comment]
If `IPHONEOS_DEPLOYMENT_TARGET` wasn't set up to `7.0` it means that [preparing script](https://github.com/cowbell/cordova-plugin-geofence/blob/master/hooks/add_swift_support.js) had not worked properly. I've changed it a little bit because it was failing if node dependencies wasn't installed. Now it is using only node core modules. From [that line](https://github.com/cowbell/cordova-plugin-geofence/blob/master/hooks/add_swift_support.js#L46) you have all steps needed to enable swift support in xcode project plus `libsqlite3.dylib` is added. Of course you can perform all of these steps manually.

**Comment by PaperMonster** [comment]
Thanks for your response. Manual Xcode project config works as you suggested. Unfortunately, the add_swift_support hook still doesn't fire. I uninstall and re-install the plugin but I didn't see any log message like [that line you mentioned](https://github.com/cowbell/cordova-plugin-geofence/blob/master/hooks/add_swift_support.js#L46) during the installation. Is that normal? Is there any setup or permission I need to check to make the script work?

**Comment by tsubik** [comment]
Try to upgrade cordova-cli to the latest version. I have `4.1.2` version currently. Add some `console.log` to the script to find out if it is fired at all.

**Comment by PaperMonster** [comment]
It really works! Yesterday I installed Crosswalk to my project so I was forced to update Cordova CLI to latest version (4.2). Then, the hook script surprisingly fired. Everything is OK now. Thanks a lot and keep up this awesome plugin. : )
