### ISSUE TITLE
Battery optimized

### ISSUE THREAD

**Issue by senthil-asdra** [cowbell/cordova-plugin-geofence#165]
Please let me know the power consumption on GPS usage. Is it optimized for battery usage? If not, any workarounds?

**Comment by tsubik** [comment]
Hey, the plugin is a wrapper on standard [android](https://developer.android.com/training/location/geofencing.html) and (iOS)[https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html] geofence API. You can look for battery usage questions for those APIs on StackOverflow.
