### ISSUE TITLE
App does not launch from IOS test flight

### ISSUE THREAD

**Issue by sumedh908** [cowbell/cordova-plugin-geofence#167]
Hello,

We are using this plugin in our ionic app and it works fine when we build and run the app from Xcode. But when we deploy the app on test flight for testing, the app does not launch at all or the app crashes. We narrowed the issue down to the Geofence plugin because once we remove the plugin from the app and upload to testflight, the app works fine.
Let me know how this can be resolved.

**Comment by rodrigodvp** [comment]
Try this:

 - First  -- > ionic platform add iOS
- Second --> ionic plugin add cordoba-plugin-geofence

In XCODE:


1- Check  build setting -> build options -> embedded content contains swift code (yes)
2- your_target -> Build Settings -> Linking -> Runpath Search Paths  ---> add  @executable_path/Frameworks
3- clean the project

This work for me, all this is done by the little code in hooks but if you add the plugin and later add the platform this piece of code isn't execute.

**Comment by sumedh908** [comment]
Thanks for the quick fix @rodrigodvp. 
The plugin now works in our Apple testflight build.
