### ISSUE TITLE
ios background notification

### ISSUE THREAD

**Issue by wallstudios** [cowbell/cordova-plugin-geofence#17]
@tsubik I've got the plugin working while the app is on in iOS7 & iOS8 but if the app is not open on iOS7 it doesn't get notifications when entering geofences. (haven't tested in 8).
Any thoughts?

**Comment by wallstudios** [comment]
I've managed to get this working.
in xcode you needed to manually tell the app to run in background mode for locations and notifications.

if you update the following to the plugin.xml file it will add it in automatically.

i've added

				<config-file target="*-Info.plist" parent="UIBackgroundModes">
					<array>
						<string>location</string>
						<string>remote-notification</string>
					</array>
				</config-file>

into here

			
			<platform name="ios">
				<hook type="after_plugin_install" src="hooks/add_swift_support.js" />
				<config-file target="*-Info.plist" parent="NSLocationAlwaysUsageDescription">
					<string>${EXECUTABLE_NAME} Would Like to Use Your Current Location Even In Background.</string>
				</config-file>
				<config-file target="*-Info.plist" parent="NSLocationWhenInUseUsageDescription">
					<string>${EXECUTABLE_NAME} Would Like to Use Your Current Location When In Use.</string>
				</config-file>
				<config-file target="*-Info.plist" parent="UIBackgroundModes">
					<array>
						<string>location</string>
						<string>remote-notification</string>
					</array>
				</config-file>		
				<config-file target="config.xml" parent="/*">
				  <feature name="GeofencePlugin">
					<param name="ios-package" value="HWPGeofencePlugin"/>
				  </feature>
				</config-file>
				<header-file src="src/ios/Geo-Bridging-Header.h" />
				<source-file src="src/ios/GeofencePlugin.swift"/>
				<source-file src="src/ios/SwiftData.swift"/>
				<source-file src="src/ios/json.swift"/>
			</platform>

**Comment by wallstudios** [comment]
one more addition...

in GeofencePlugin.swift I've added in the default sound to the notification.
I've also added Badge numbers as well but haven't figured out how to clear them from the app yet.

			func notifyAbout(geo: JSON) {
				log("Creating notification")
				var notification = UILocalNotification()
				notification.timeZone = NSTimeZone.defaultTimeZone()
				var dateTime = NSDate()
				notification.fireDate = dateTime
				notification.soundName = UILocalNotificationDefaultSoundName;
				//notification.applicationIconBadgeNumber = 1;
				notification.alertBody = geo["notification"]["text"].asString!
				UIApplication.sharedApplication().scheduleLocalNotification(notification)
			}

**Comment by pedroabreu** [comment]
Nice work @wallstudios, can you make a PR with those changes ?

**Comment by tsubik** [comment]
I've applied those changes. Thanks!
