### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by marcovisona** [cowbell/cordova-plugin-geofence#172]
Hello,
   it is expected a swift 3 version of this plugin? At the moment it doesn't compile in Xcode 8

Thank you very much

**Comment by Marjoel** [comment]
Hi,
I'm in the same way, after I've updated my Xcode, my app with this plugin doesn't compile anymore.

Is It expected a Swift 3 version?

Thanks.

**Comment by ezazwar1** [comment]
+1

**Comment by ElieSauveterre** [comment]
+1

**Comment by Wade-BuildOtto** [comment]
+1

**Comment by friedolinfoerder** [comment]
+1

**Comment by tsubik** [comment]
Duplicate of https://github.com/cowbell/cordova-plugin-geofence/issues/215
