### ISSUE TITLE
Phonegap Build iOS submission fails with SwiftSupport error.

### ISSUE THREAD

**Issue by kleeb** [cowbell/cordova-plugin-geofence#176]
I am using the newest Phonegap Build: cli-6.3.0 (comes with cordova-ios 4.2.0)
`<plugin name="cordova-plugin-geofence" spec="0.6.0" />`

along with (to match iOS7+)
`<preference name="deployment-target" value="7.0" />`

The ipa package builds correctly, but iTunesConnect is not letting it go with an error: "Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it."

Adding 
`<plugin name="cordova-plugin-add-swift-support" spec="1.3.2" />` 
is not helping much.

Running this dirty workaround script https://github.com/huhuvipi/VH_ipa_packger/blob/master/package_ipa.sh on the ipa helps, but would be good to have the proper fix here.

**Comment by tsubik** [comment]
Please try to set `swift-version` for PhoneGap project, check updated readme section here https://github.com/cowbell/cordova-plugin-geofence#ios. Closing for now, please feel free to reopen if problem still occurs.
