### ISSUE TITLE
geofences not added kCLErrorDomain

### ISSUE THREAD

**Issue by Gerald1985** [cowbell/cordova-plugin-geofence#186]
Would you please let me know if this issue is supported? AddOrUpdate method is returning KCLErrorDomain code=5

2016-10-27 22:24:44.260387 xxxxxx[529:67449] GeofencePlugin - AddOrUpdate geo: {
  "transitionType" : 1,
  "notification" : {
    "id" : 26597316298968,
    "title" : "SBARRO",
    "smallIcon" : "res:\/\/icon",
    "icon" : "file:\/\/img\/geofence_icon.png",
    "openAppOnClick" : true,
    "text" : "Sbarro"
  },
  "id" : "0-SBARRO-19",
  "radius" : 300,
  "longitude" : -86.249033,
  "latitude" : 12.103899
}
2016-10-27 22:24:44.286321 xxxxxx[529:67423] GeofencePlugin - Monitoring region 0-SBARRO-19 failed Error Domain=kCLErrorDomain Code=5 "(null)"

Am I missing something?  why geos are not added to Monitoring task.

**Comment by marvi14** [comment]
Could you fix this? I'm facing the same issue

**Comment by tsubik** [comment]
Check [limitations of this plugin](https://github.com/cowbell/cordova-plugin-geofence#known-limitations), that could be the reason as @marvi14 mentioned, no more than 20 regions is allowed for iOS.
