### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by ormit** [cowbell/cordova-plugin-geofence#190]
Getting the following error on build : 

/cordova-plugin-geofence/GeofencePlugin.swift:35:23: error: expected expression in list of expressions
           selector: #selector(GeofencePlugin.didReceiveLocalNotification(_:))

Any ideas ?

**Comment by tsubik** [comment]
Probably duplicate of https://github.com/cowbell/cordova-plugin-geofence/issues/215
