### ISSUE TITLE
NotificationData overrides with recently pushed notification.

### ISSUE THREAD

**Issue by Nagapandi** [cowbell/cordova-plugin-geofence#195]
when i get the notification, the lastly added custom object data is shown for all notifications instead of the corresponding custom object. 
#156 
Please let me know how to get the respective object of the notification message. 

here the code

 for (i = 0; i < 5; i++) {                           
                        var    g[i] = {
                                id: i,
                                latitude: ,
                                longitude: ,
                                radius: ,
                                transitionType: TransitionType.ENTER,
                                notification: {
                                    id: i,
                                    title:"Title",
                                    text: "Text",
                                    openAppOnClick: true,
                                    data: {
                                        id: i,
                                        title: Title,
                                        text: Text }                                                              
                                           }
                                    }   
}

**Comment by Nagapandi** [comment]
got the solution for this issue 
in GeoNotificationNotifier.java file you need to modify the below line. 

PendingIntent resultPendingIntent = stackBuilder.getPendingIntent(
                    **<Some_Unique_Value>**, PendingIntent.FLAG_UPDATE_CURRENT);

**Comment by tsubik** [comment]
Fixed in #206
