### ISSUE TITLE
ios support

### ISSUE THREAD

**Issue by wallstudios** [cowbell/cordova-plugin-geofence#2]
Hi There,
More of a question than an issue. Any idea when you might be adding ios support?
thanks.

**Comment by tsubik** [comment]
Support for iOS >=7 added :smile:

**Comment by wallstudios** [comment]
@tsubik good stuff :) I'll test and let you know any feedback. Thanks for your work on this.

**Comment by wallstudios** [comment]
Failed to install 'com.cowbell.cordova.geofence':Error: Cannot find module 'glob' @tsubik 
any idea?

**Comment by wallstudios** [comment]
got it to work.

**Comment by wallstudios** [comment]
well got it to install.
I'm now having issues.
-[CLLocationManager requestAlwaysAuthorization]: unrecognized selector sent to instance 0x17d03f50

**Comment by wallstudios** [comment]
@tsubik a couple of fixes for you for iOS7 support...

NSProcessInfo().isOperatingSystemAtLeastVersion
Isn't supported by iOS7 so this errors.


			let TAG = "GeofencePlugin"
			//let iOS8 = NSOperatingSystemVersion(majorVersion: 8, minorVersion: 0, patchVersion: 0)
			let iOS8 = floor(NSFoundationVersionNumber) > floor(NSFoundationVersionNumber_iOS_7_1)
			let iOS7 = floor(NSFoundationVersionNumber) <= floor(NSFoundationVersionNumber_iOS_7_1)

changed

			        if NSProcessInfo().isOperatingSystemAtLeastVersion(iOS8) {
			            promptForNotificationPermission()
			        }
to

					if iOS8 {
						promptForNotificationPermission()
					} 
also changed this from

				locationManager.requestAlwaysAuthorization();

to

			if iOS8 {
				locationManager.requestAlwaysAuthorization();
			}

**Comment by tsubik** [comment]
:+1:  changes applied. Thanks!

**Comment by wallstudios** [comment]
@tsubik  in the new version you have line 159 saying if (iOS7)

should be

			if (iOS8) {
				locationManager.requestAlwaysAuthorization()
			}

**Comment by tsubik** [comment]
Duh. You're right. Thanks again!
