### ISSUE TITLE
Why? lib-file: gson-2.3 include .

### ISSUE THREAD

**Issue by JUN-KOBAYASHI** [cowbell/cordova-plugin-geofence#203]
Do I need to keep the gson library locally?
Because it conflicts with other plugins, can not you change if there is no problem?

plugin.xml:
<lib-file src="src/android/libs/gson-2.3.jar" />

fixit:
<framework src="com.google.code.gson:gson:2.4" />

**Comment by tsubik** [comment]
This plugin uses gson library, that's why it's included. Please look up for libraries versions conflict resolutions on StackOverflow.
