### ISSUE TITLE
publish a new version

### ISSUE THREAD

**Issue by dominikstrasser** [cowbell/cordova-plugin-geofence#208]
Hey.

I was trying to install the plugin as described but failed due to the "swift 3 problem". 
I did not know i had to install the plugin `cordova-plugin-add-swift-support` by myself. 
It is listed in the dependencies of the current source code but it is not in the published version.

could you please publish a new version so it is installed as a dependency?
thanks :)

**Comment by tsubik** [comment]
Published :) https://github.com/cowbell/cordova-plugin-geofence/commit/43f508fc9e138bf33365c5ff9a746c83cf38d0bf
