### ISSUE TITLE
iOS: Suggested app on iOS 8 lock screen

### ISSUE THREAD

**Issue by ohh2ahh** [cowbell/cordova-plugin-geofence#25]
Thank you for your useful plugin. My goal is to display my app as a suggested app on the iOS 8 lock screen. Is it somehow possible to achieve this using your plugin? It should be [possible](http://stackoverflow.com/questions/26790833/is-it-possible-to-put-a-shortuct-to-my-app-as-a-suggested-app-on-the-lock-screen) with a geofence.

**Comment by tsubik** [comment]
I don't know if it possible to manually do something like this. This question is more likely to be on StackOverflow.
