### ISSUE TITLE
onTransitionReceived do not execute any callback while in background (Phonegap/Cordova)

### ISSUE THREAD

**Issue by mateusredfield** [cowbell/cordova-plugin-geofence#264]
I am using phonegap cordova plugin, to test in android 4.4. The problem is: I want to run some code when a region is entered and the app is in background, is that possible with this plugin?

**Comment by nilsk123** [comment]
This is expected behaviour. The javascript can't execute because the web view is suspended when app isn't in the foreground. You can however handle this on the native side of things.
