### ISSUE TITLE
Build fail on phonegap build

### ISSUE THREAD

**Issue by QuentinFchx** [cowbell/cordova-plugin-geofence#31]
When using this plugin with Phonegap Build, it fails during the compilation.

```
The following build commands failed:
	CompileSwift normal arm64 /project/PGProject/Plugins/com.cowbell.cordova.geofence/GeofencePlugin.swift
	CompileSwift normal arm64 /project/PGProject/Plugins/com.cowbell.cordova.geofence/SwiftData.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
```
[Full stack trace](http://pastebin.ca/2962761)

I have absolutely no knowledge of Swift. @tsubik could you help me please ?

**Comment by tsubik** [comment]
I am not an expert either :smile:. That part of plugin is my only code written in swift so far. Try to open project in xcode and make sure bridging headers are correct. It should be main `Bridging-Header.h` which basically import others "bridging headers" from the project (it should be generated by `add_swift_support` hook) and `Geo-Bridging-Header.h`. I've tried to make my plugin compatible with other swift plugins.

**Comment by QuentinFchx** [comment]
Yep, it was an issue with bridging header :)
Thanks for your help ! :+1:

**Comment by rodneyworkman291** [comment]
I am having this same issue as posted below in stackoverflow.  I can open my project in xcode but I am not sure how to make sure bridging headers are correct.  

http://stackoverflow.com/questions/33828532/phonertc-build-issues-in-phonegap-bridging-header-h-issue

**Comment by johnrobertcobbold** [comment]
@tsubik Following updating Cordova to version 4 and https://issues.apache.org/jira/browse/CB-10072, I had to change the content of SWIFT_OBJC_BRIDGING_HEADER and add 'Plugins' to the path for the building to find the header file. Not sure how other plugins are doing, perhaps you want to locate the bridge in the PROJECT_NAME folder, not PROJECT_NAME/PLUGINS anymore? For your consideration.

**Comment by scriby** [comment]
I am encountering this issue on phonegap build. Anyone know how to resolve it there?

**Comment by scriby** [comment]
I was able to resolve this by adding `<preference name="deployment-target" value="7.0" />` to config.xml.
