### ISSUE TITLE
region persistence between relaunches

### ISSUE THREAD

**Issue by maxpli** [cowbell/cordova-plugin-geofence#33]
Hey Tomasz,
thanks for the cool plugin. I was wondering if regions persist between relaunches as described here:
https://developer.apple.com/library/mac/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html

"In this case, the options dictionary passed to the application:didFinishLaunchingWithOptions: method of your app delegate contains the key UIApplicationLaunchOptionsLocationKey to indicate that your app was launched because of a location-related event."

thanks a lot,
max

**Comment by tsubik** [comment]
Hey @maxpli , sorry for not answering. Is something not working?

**Comment by maxpli** [comment]
hey Tomasz, i am currently using another geofence plugin, which seems to have a problem with region persistence. so i was wondering if this is an issue in your plugin as well before switching. thanks for your help. max

**Comment by tsubik** [comment]
On iOS number of regions is limited to 20. Maybe this is the problem. I haven't tested that though. There were no issues about persisting regions, but I cannot guarantee. iOS implementation is nothing special so far, just using CLLocationManager.

**Comment by maxpli** [comment]
thanks Tomasz
