### ISSUE TITLE
Background geo-location

### ISSUE THREAD

**Issue by m-menon** [cowbell/cordova-plugin-geofence#41]
hi,

Firstly thanks a ton for this useful plugin. I think I can put this to good use in one of the Apps. But me being new to Android / Java, have this quick question. I may also be needing to do a background geolocation update. So I was thinking that instead of having another service or plugin do a background geolocation update, can I use this plugin to update a remote server with it's location co-ordinates? If yes where exactly do you think I should fit in the code to post the latitude / longitude data.

And also does this run as as service? I mean even after a reboot will it start up automatically?

Thanks a ton,
M&M

**Comment by tsubik** [comment]
Hey @m-menon . I am afraid this plugin is only for monitor geofences. If you want to send some data to remote server on geofence transition, you could write some native code and place it somewhere [here](https://github.com/cowbell/cordova-plugin-geofence/blob/master/src/android/ReceiveTransitionsIntentService.java#L85). Answering your last question: Yes it is working after device reboot.

**Comment by m-menon** [comment]
hi tsubik,

Oke thanks a ton for the information. I'll add some code at the location you mentioned and try pushing the location information to the server.

Cheers,
M&M
