### ISSUE TITLE
EXC_BAD_INSTRUCTION (code=EXC_i386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by DataHerder** [cowbell/cordova-plugin-geofence#46]
Hi Tsubik,

On line 178 in GeofencePlugin.swift file geoNotification data set to .asDouble! creates this exception.  If I comment out and force a literal double, it breaks somewhere else.  This is happening trying to add or update a geofence.

![screen shot 2015-04-30 at 11 29 53 am](https://cloud.githubusercontent.com/assets/361400/7419791/546064a8-ef2c-11e4-8b12-56ba89da430f.png)
![screen shot 2015-04-30 at 11 30 01 am](https://cloud.githubusercontent.com/assets/361400/7419794/564e2ade-ef2c-11e4-9ca3-9119003016dc.png)

Can you verify that this is also happening on your end?

Thanks,

**Comment by tsubik** [comment]
I'm not having this issue. I am currently using Xcode version 6.3.1.

**Comment by DataHerder** [comment]
Hey tsubik~  Just came back to tell you that I found out why.  It's because it expects the "id" to be a String not an int.  As you can see from the output the id is an int coming back from the db, I have to cast the id to string before I feed the plugin.  Perhaps this should be a little more forgiving for integer id's by checking for int values and casting it to a string in the plugin near `let id = geoNotification["id"].asString`.  Just my 2 cents, otherwise people just have to remember if they are using a unique identifier in the db as an auto increment rather than UIID or string, cast it to a string or the plugin will break.  asString() will return a nil and break it.

**Comment by tsubik** [comment]
@DataHerder thanks. I will :)
