### ISSUE TITLE
Can't Identify Which Transition Type Occurred When Using TransitionType = 3

### ISSUE THREAD

**Issue by jgcaruso** [cowbell/cordova-plugin-geofence#49]
When using TransitionType = 3 there is not way to identify if it was an 'entered' or 'exited' event that triggered the event. Could the 'geo' object be modified in some way to identify if it was an Enter or Exit transition that triggered the current transition call?

The only way to currently detect this is to create separate Enter and Exit geofences, which on iOS uses up 2 of the 20 allowed fences (instead of just 1).

**Comment by jgcaruso** [comment]
FYI I'm perfectly happy to implement this myself and submit a pull request, but if I do I want to make sure to implement it in a way that you're happy with. I considered updating the geo object that gets sent to the js and NotificationCenter listeners/handlers transitionType to 1 or 2 depending on which handler it came from (enter or exit), but if you'd rather not have it happen that way another property can be added to the geo object (something like actualTransitionType) with the appropriate number.

I just won't be able to implement this for Windows Phone because I am not really setup to develop for it.

**Comment by tsubik** [comment]
Hey @jgcaruso your proposition to update transitionType in geo object is good. Don't worry about Windows Phone.

**Comment by raldred** [comment]
:+1: happy to assist as this is something i've just discovered also.
