### ISSUE TITLE
Customize vibration pattern for notification

### ISSUE THREAD

**Issue by tsubik** [cowbell/cordova-plugin-geofence#5]
Should be possible to change vibration pattern for the notification. The best option will be a few predefined patterns and if it is possible setting custom pattern e.g. (1000 1000 1000) - vibrate 3 times each 1 sec long.

**Comment by Haice** [comment]
Kindly Update the Plugin XML to include Vibrate Permission on Android... I was getting a 'App not responding' message on one of my test tablets every time there is a notification until i manually added the permission.

**Comment by tsubik** [comment]
Reference b5be4e22b27bca9e
