### ISSUE TITLE
geofence.onNotificationClicked is not called on Android 5.1

### ISSUE THREAD

**Issue by rudza** [cowbell/cordova-plugin-geofence#51]
When clicked on Notification: 
 - On Android 4.4.2: app opens and 'onNotificationClicked' is called;
 - On Android 5.1: app opens but 'onNotificationClicked' is not called;

**Comment by graphicgeek** [comment]
I'm having the same issue.

**Comment by moritzio** [comment]
I am also having this issue. Any update?

**Comment by nwidal** [comment]
Same issue on Android 5.1.1 - Does it maybe have something to do with deprecated android.support.v4 stuff, moved to new libraries? I don't have the time nor the knowledge to investigate further. 
I really depend on a click event fired on notification click - please investigate =)

**Comment by Tempus35** [comment]
Interesting, I am on Android 6.0 and I got it working when I made sure that I had the data object under the notification object in the fence and the data object has data.

**Comment by tsubik** [comment]
Never got this issue. Feel free to reopen if you find this doesn't work.
