### ISSUE TITLE
on iOS, I cannot add geofence dynamically without the app freezing

### ISSUE THREAD

**Issue by lamyju** [cowbell/cordova-plugin-geofence#52]
Hi there,

I first tested adding a static geofence and it worked fine.
I then worked off a list of location. 
I calculate the distance from the device location to each lat/long referenced in the list and get the 20 closest distance to me.

Once I have an array of 20 objects, I loop through each of them to add them as geofence but it doesn't work. I tried 1, 3, 5, 10. Any number makes the app freeze.

I took a step back and started thinking maybe my location array is wrong so I hardcoded basic lat/long following the static example that worked but no luck.

One question is:
Can I loop through geofence.addOrUpdate indefinitely passing new objects or can I only create one per geofenceService? I'm really confused as to why it is not working.

Error is : 
![screen shot 2015-05-16 at 1 50 17 am](https://cloud.githubusercontent.com/assets/462197/7656458/f292ca74-fb6d-11e4-9b0c-356d371f29db.png)
![screen shot 2015-05-16 at 1 51 28 am](https://cloud.githubusercontent.com/assets/462197/7656494/21c115bc-fb6e-11e4-8998-95ae569cf5cb.png)
![screen shot 2015-05-16 at 1 51 40 am](https://cloud.githubusercontent.com/assets/462197/7656495/22e07ea6-fb6e-11e4-814e-816d3c6346ec.png)

Any help or advice would be greatly appreciated.

Cheers

**Comment by lamyju** [comment]
Hi there, any updates on the above? Am I doing something incorrectly?

Cheers

**Comment by tsubik** [comment]
Hey, you can pass an array or single geofence to addOrUpdate function. Can you paste any system.log from simulator or phone filtered with phrase GeofencePlugin. There should be some logs from plugin.

**Comment by tsubik** [comment]
I'm not able to reproduce that.
