### ISSUE TITLE
Help me out How to Bind Geofence methods in My Application

### ISSUE THREAD

**Issue by IonicUser** [cowbell/cordova-plugin-geofence#54]
Hi cowbell,
Please Guide me How to bind Geofence methods in MAP application....Am using Ionic frame works and AngularJS. But when calling those methods from My application there is no response.....I installed geofence Plugin.

**Comment by andiCR** [comment]
I am using the plugin without any problems on Ionic. The main thing is to be able to correctly set the geofences and initialize the plugin. What platforms are you having trouble with? Any code you can share of what you're trying to do?

**Comment by tsubik** [comment]
Hey @IonicUser please take a look at https://github.com/cowbell/ionic-geofence. Example project is also built with ionic framework. I am closing issue, because it is not relevant to plugin itself.
