### ISSUE TITLE
Plugin breaks ios build - VS2015 Tools for Apache Cordova

### ISSUE THREAD

**Issue by antwan2093** [cowbell/cordova-plugin-geofence#59]
Adding this plugin prevents build on ios platform for my app. Arguments to path.join must be strings.

http://stackoverflow.com/questions/30581667/build-fails-after-adding-geofence-plugin

**Comment by tsubik** [comment]
Hey, thanks for the issue. I've pushed some changes to [add_swift_support.js](https://github.com/cowbell/cordova-plugin-geofence/blob/cb7434ad660a498f4bbcd9bae4e3c000ee9d491b/hooks/add_swift_support.js) hook. You can try install plugin from master or just replace that file.

**Comment by antwan2093** [comment]
Thank you so much, that was very fast. Its people like you that make me love development!

Thanks again, will let you know how it goes.

Anthony

**Comment by antwan2093** [comment]
Hmmm ive reinstalled and now I'm getting the following error:

 ```Severity	Code	Description	Project	File	Line
Error		Error Domain=NSCocoaErrorDomain Code=260 "The file “SwiftData.d” couldn’t be opened because there is no such file." UserInfo=0x7fcfee8848a0 {NSFilePath=/Users/anthonyhumphreys/remote-builds/builds/1026/cordovaApp/platforms/ios/build/3dp.build/Debug-iphoneos/3dp.build/Objects-normal/armv7/SwiftData.d, NSUnderlyingError=0x7fcfee884b20 "The operation couldn’t be completed. No such file or directory"}. User info: {	3dp	C:\Users\Antwan\documents\visual studio 2015\Projects\3dp\3dp\Details	1```

Is this an environmental issue?

**Comment by tsubik** [comment]
What is your remote mac configuration? To build plugin you must have 10.10 Yosemite, xCode 6.3 to support swift 1.2. You can try older version of plugin (below 0.4).

**Comment by antwan2093** [comment]
I will check this in the morning, thanks. Its via vs-mda-remote if I hadn't said before,


Thanks






Sent from Windows Mail





From: Tomasz Subik
Sent: ‎Wednesday‎, ‎3‎ ‎June‎ ‎2015 ‎23‎:‎00
To: cowbell/cordova-plugin-geofence
Cc: antwan2093





What is your remote mac configuration? To build plugin you must have 10.10 Yosemite, xCode 6.3 to support swift 1.2. You can try older version of plugin (below 0.4).

**Comment by tsubik** [comment]
Closed due inactivity.
