### ISSUE TITLE
Hangs on 'Obtaining current location...' loader screen when deploying to Android device

### ISSUE THREAD

**Issue by EIrwin** [cowbell/cordova-plugin-geofence#62]
I cloned this repo and deployed it to my android device.

When I click the (+) to add a geofence, the `Obtaining current location...` screen pops up and it just hangs.

I have tried different settings combinations between the wifi and location services and none of them cause it to not hang.

It works fine when I run in the browser, but not on my android device.

![screenshot_2015-06-16-21-06-22](https://cloud.githubusercontent.com/assets/6673161/8199522/cfabc10c-146b-11e5-953f-aaf0f72f2c0b.png)

**Comment by tsubik** [comment]
Hey @EIrwin this looks like geolocation plugin issue, can you check logs through `adb logcat`

**Comment by EIrwin** [comment]
@tsubik Thanks for the prompt response.

I am working on pinpointing the issue.

A weird correlation I have made is that when I compile down to android on my PC, it hangs. However when I compile down to android on my macbook, it works. 

Let me run `adb logcat` and see if I can find the cause.

**Comment by EIrwin** [comment]
@tsubik I ran the following

`adb logcat | grep -i "location"`

and got the following which seems to be directly related to the problem.

```
I/chromium(25538): [INFO:CONSOLE(20306)] "Obtaining current location...", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (20306)
D/LocationManagerService(  749): getProviders()=[passive, gps]
D/LocationManagerService(  749): request 443c3c60 fused Request[ACCURACY_BLOCK fused requested=0 fastest=0] from com.tsubik.ionicgeofence(10316)
D/LocationManagerService(  749): provider request: fused ProviderRequest[ON interval=0]
D/LocationManagerService(  749): Location listener died
I/LocationManagerService(  749): remove 443c3c60 by com.tsubik.ionicgeofence
D/LocationManagerService(  749): provider request: fused ProviderRequest[OFF]
W/GeofencerStateMachine( 1245): Ignoring removeGeofence because network location is disabled.
```

This is not ALWAYS the case, but majority of the time it is. What is also happening is, it will fail or wait for awhile and hang with the loading screen and then 10 or more minutes will go by, and then it will proceed to the geofence detail page. Any ideas?

**Comment by EIrwin** [comment]
@tsubik As it turns out. It seem like this is something related to the 'High accuracy setting on my Samsung Galaxy S5' It was not on high accuracy, which seemed like it really had a hard time resolving the location correctly.

I was able to fix this by changing my Location setting from `GPS Only` to `High Accuracy`

**Comment by tsubik** [comment]
@EIrwin great to hear that you resolved the problem. Thanks for letting me know
