### ISSUE TITLE
Unable to install plugin for  android

### ISSUE THREAD

**Issue by coddypotter** [cowbell/cordova-plugin-geofence#63]
This is the message i am getting. I am able to install all the other plugins except this.
![untitled](https://cloud.githubusercontent.com/assets/10388932/8504159/2546f77c-2181-11e5-8fb3-408bc7315cfb.png)

**Comment by tsubik** [comment]
Hey @coddypotter. Maybe this is related to #64

**Comment by tsubik** [comment]
Closed due inactivity.
