### ISSUE TITLE
Errors.

### ISSUE THREAD

**Issue by coddypotter** [cowbell/cordova-plugin-geofence#67]
Errors after importing in eclipse
![err](https://cloud.githubusercontent.com/assets/10388932/8721514/064a8f2a-2b70-11e5-9e36-a4134601c297.png)

**Comment by tsubik** [comment]
Make sure you have `cordova-plugin-googleplayservices` installed properly. It is a dependent plugin, should be installed along with the main plugin automatically. You should have `google-play-services.jar` file in `platforms/android/libs` directory.
