### ISSUE TITLE
Android: run at startup

### ISSUE THREAD

**Issue by kevinleequinn** [cowbell/cordova-plugin-geofence#68]
greetings,

for Android, if geofences are registered with the OS then why do you need the permission "run at startup"?

**Comment by tsubik** [comment]
As far I know they were not persisted after reboot in version 4.x. Maybe something has changed since version 5.0, but I am not aware of those changes and I haven't tested if they persist or not on after reboot.

**Comment by kevinleequinn** [comment]
gotcha, thx!
