### ISSUE TITLE
iOS failing to build on Phonegap Build

### ISSUE THREAD

**Issue by kevinleequinn** [cowbell/cordova-plugin-geofence#70]
hello again, I have been testing this on Android for a few weeks now and it works perfectly.

but iOS is failing to build on Phonegap Build.  I included in my config.xml to not do iOS6 (preference name="deployment-target" value="7.0") but it still fails to compile.  error:

cordova-plugin-geofence/GeofencePlugin.swift:20:49: error: use of undeclared type 'CDVPlugin'

full build log here:  https://www.dropbox.com/s/v6codigjsxgfe16/build.txt?dl=0

ps - I am using the npm version (https://www.npmjs.com/package/cordova-plugin-geofence)

**Comment by shtaif** [comment]
Any progress with this?
Would too like to have it working with Phonegap Build :)

**Comment by kevinleequinn** [comment]
not yet.  still works well on Android.

**Comment by rodneyworkman291** [comment]
I am having the same issue.  Any progress on your end?

**Comment by kevinleequinn** [comment]
nope, haven't messed with it lately.

**Comment by tsubik** [comment]
I think this should be resolved by 8242ef1.
