### ISSUE TITLE
UIBackgroundModes location required?

### ISSUE THREAD

**Issue by gabecoyne** [cowbell/cordova-plugin-geofence#71]
I'm getting pushback from the apple store about UIBackgroundModes location being required.

They say to use region monitoring (which you are doing).

Is there a reason this plugin requires background location? 

It seems like RegionMonitoring is supposed to handle that.

Can you remove that as a dependency of this plugin?

http://stackoverflow.com/questions/13511340/uibackgroundmodes-location-and-significant-location-changes-with-region-monitori

**Comment by tsubik** [comment]
Yes this is not the first complaint against this (related #60). Someone else complained about adding that permission the other day, though. Anyway, I am going to remove that permission requirement.
