### ISSUE TITLE
window.geofence is undefined

### ISSUE THREAD

**Issue by florianbepunkt** [cowbell/cordova-plugin-geofence#74]
Hey,

I created a new ionic app and then added the cordova-plugin-geofence.
In my app.js inside my $ionicPlatform.ready(function() function I want to initialize geofence with
window.geofence.initialize();

But in my console it always says window.geofence is undefined. Can someone help me what I'm doing wrong. The plugin installation went without any errors.

Thanks

**Comment by florianbepunkt** [comment]
I did some digging… I encounter this problem only when using Ionic. When I create an app with cordova create myproject and install the plugin, I can access the window.geofence object.

But with Ionic it says it is undefined… have somebody else encountered the same issue? Can somebody please help? Thanks

**Comment by PaperMonster** [comment]
Did you run on device or browser? Cordova plugins always be undefined on browsers. If you're running on device, giving plugin version and other information from command `ionic info` would help pinpointing the problem faster.

**Comment by florianbepunkt** [comment]
Thanks for your reply. I now tested it within ios emulator and read out the console with safari developer tools. Now the object is not undefined anymore (but gives another error). Here's what I've done.

I used a new ionic tabs starter app `$ionic start MyApp tabs`

I added the plugin. First strange thing. I had to run `$ionic build ios` before I added the plugin (otherwise the CLI threw an error).

I only changes my app.js now as following

```javascript
$ionicPlatform.ready(function() {
   window.geofence.initialize();
})
```
In the console it reads `TypeError: Object is not a constructor (evaluating 'new Promise')`
Here's the `ionic info` output:
```
Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b 
```

**Comment by florianbepunkt** [comment]
Hi @PaperMonster,

the issue you opended and your hint already helped tremendouly. I fixed the error as you suggested here: https://github.com/cowbell/cordova-plugin-geofence/issues/75

Right now I can initialize the plugin and add geofences. But it seems I cant detect any changes to them:

I have all my code inside the `$ionicPlatform.ready` function:

But when I give different location coordinates in the iOS emulator, jumping to the coodinates defined in my geofences, nothing happens. Can you help?

Thanks,
Florian

```javascript
$ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);

    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleLightContent();
    }

    console.log('device is now ready');
    window.geofence.initialize();

    console.log(window.geofence);

    window.geofence.addOrUpdate({
        id:             'home', //A unique identifier of geofence
        latitude:       48.1809125, //Geo latitude of geofence
        longitude:      16.334053, //Geo longitude of geofence
        radius:         100, //Radius of geofence in meters
        transitionType: 3, //Type of transition 1 - Enter, 2 - Exit, 3 - Both
        notification: {         //Notification object
            id:             1, //optional should be integer, id of notification
            title:          'Home', //Title of notification
            text:           'You are at home', //Text of notification
            smallIcon:      '', //Small icon showed in notification area, only res URI
            icon:           '', //icon showed in notification drawer
            openAppOnClick: true,//is main app activity should be opened after clicking on notification
            vibration:      1, //Optional vibration pattern - see description
            // data:           Object  //Custom object associated with notification
        }
    }).then(function () {
        console.log('Geofence successfully added');
    }, function (reason) {
        console.log('Adding geofence failed', reason);
    });

    window.geofence.addOrUpdate({
        id:             'underground station', //A unique identifier of geofence
        latitude:       48.18130596, //Geo latitude of geofence
        longitude:      16.3311884, //Geo longitude of geofence
        radius:         50, //Radius of geofence in meters
        transitionType: 3, //Type of transition 1 - Enter, 2 - Exit, 3 - Both
        notification: {         //Notification object
            id:             1, //optional should be integer, id of notification
            title:          'underground', //Title of notification
            text:           'You are at underground', //Text of notification
            smallIcon:      '', //Small icon showed in notification area, only res URI
            icon:           '', //icon showed in notification drawer
            openAppOnClick: true,//is main app activity should be opened after clicking on notification
            vibration:      1, //Optional vibration pattern - see description
            // data:           Object  //Custom object associated with notification
        }
    }).then(function () {
        console.log('Geofence successfully added');
    }, function (reason) {
        console.log('Adding geofence failed', reason);
    });

    window.geofence.getWatched().then(function (geofencesJson) {
        var geofences = JSON.parse(geofencesJson);
        console.log('my geofences', geofences);
    });

    window.geofence.onTransitionReceived = function (geofences) {
        geofences.forEach(function (geo) {
            console.log('Geofence transition detected', geo);
        });
    };

  });
```

**Comment by florianbepunkt** [comment]
Hey Papermonster,

I deleted my comment from before… it seems to work now. Thanks for the other issue you opened it… fixing this solved the problem + running it on the device.

One more thing, if you could help me out once more. Is there a way to specify options for this plugin, such as accuracy or the frequency how often the current location is checked?

I tested some geofences that are relatively close to each other (about 100 metres)… I registered them each with a radius of 10 but when I jumped between the coordinates for both I always got an enter event for both geofences. When I choose some geofences that are further part this does not occur.

Thanks,
Florian

**Comment by PaperMonster** [comment]
I don't think you can specify accuracy or frequency unless modifying the plugin, as this plugin relies on standard iOS' region monitoring feature which is based on 'significant location change'. [A discussion at Stackoverflow](http://stackoverflow.com/questions/17790350/minimum-radius-for-ios-clregion-feature-of-locatinmanager) pointed out that the location mainly comes from surrounding Wi-Fi hotspots and cellular towers, not GPS. Also, region entrance/exit only triggers when crossing boundary by at least ~200m, as following quote from [the documentation](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html#//apple_ref/doc/uid/TP40009497-CH9-SW11):

> When testing your region monitoring code in iOS Simulator or on a device, realize that region events may not happen immediately after a region boundary is crossed. To prevent spurious notifications, iOS doesn’t deliver region notifications until certain threshold conditions are met. Specifically, the user’s location must cross the region boundary, move away from the boundary by a minimum distance, and remain at that minimum distance for at least 20 seconds before the notifications are reported.

> The specific threshold distances are determined by the hardware and the location technologies that are currently available. For example, if Wi-Fi is disabled, region monitoring is significantly less accurate. However, for testing purposes, you can assume that the minimum distance is approximately 200 meters.

Therefore, regions smaller than 150m radius placed too close together are unlikely to be caught by region monitoring correctly.

If you really need high-accuracy region monitoring, you might consider modifying the plugin to utilize standard location (and/or background mode setup) which continuously track the location for the specified level of accuracy, at the cost of more battery draining.

**Comment by florianbepunkt** [comment]
@PaperMonster Thanks a lot for your help and the explanation.

**Comment by StevenMapes** [comment]
I'm having this issue with geofence and phonegap.

I created a new phonegap project, installed the plugin, edit the config.xml as has been suggested else where

```
npm install -g phonegap
phonegap create geofenceTest com.test.geofence geofenceTest
```

```
phonegap plugin add cordova-plugin-add-swift-support
phonegap plugin add cordova-plugin-geofence

```
Edit config.xml to change the min version from 14 to 16
`    <preference name="android-minSdkVersion" value="16" />`

Edit the index.html
```
    <script type="text/javascript">
        app.initialize();

        try {
            window.geofence.initialize(function(){console.log(1)}, function(){ console.log(2)}).then(function(){console.log(3)});
        } catch (e) {
            console.log(e)
        }
    </script>
```
When I then run the app (I'm using Webstorm with Phonegap/cordova plugin installed, running the serve command for android ) and I just receive this exception everytime

`[phonegap] [console.log] TypeError: Cannot read property 'initialize' of undefined`
