### ISSUE TITLE
onNotificationClicked not firing in ANdroid 4.1.2

### ISSUE THREAD

**Issue by coddypotter** [cowbell/cordova-plugin-geofence#83]
Hello,
I am trying to open a my app via notification but not getting any data when put alert in onNotificationClicked function. App opens but onNotificationClicked  not working.

**Comment by Tempus35** [comment]
Is there data in the notification, IE when you create the notifiction in the addOrUpdate function does it have { ... , ... , notification: { ... , ... , data{}}. It appears the click notification stuff is not setup/called unless that data object exists and is not null.

**Comment by tsubik** [comment]
Also don't forget to call [initalization function](https://github.com/cowbell/cordova-plugin-geofence#plugin-initialization). I'm closing this for now.
