### ISSUE TITLE
In README add hint that GooglePlayServices are required

### ISSUE THREAD

**Issue by freebird2** [cowbell/cordova-plugin-geofence#88]
From what I understand GoogleServices are required to use this plugin.
Otherwise saving a geofence by pressing + button fails...

Thus a hint ('requirements on Android: GooglePlayServices required') in 
https://github.com/cowbell/cordova-plugin-geofence/blob/master/README.md
would be helpful.

Not all people have PlayServices installed :-)

Tested on Samsung Neo with services installed / Nexus 4 without services

**Comment by tsubik** [comment]
Thanks for hint :+1:
