### ISSUE TITLE
Example is a little outdated

### ISSUE THREAD

**Issue by spottuit** [cowbell/cordova-plugin-geofence#90]
When I was looking at the documentation I saw that you need to specify the **transitionType** with a number (1,2 or 3), but there is still a constant used in the example. You can see this below:

![image](https://cloud.githubusercontent.com/assets/9430751/10435599/482c8d52-7121-11e5-902b-b76f797c991c.png)

**Comment by tsubik** [comment]
But this constant is a [corresponding number](https://github.com/cowbell/cordova-plugin-geofence/blob/master/www/TransitionType.js), this is only helper to make the code more readable.
