### ISSUE TITLE
Status for 'Both'

### ISSUE THREAD

**Issue by derek1988ec** [cowbell/cordova-plugin-geofence#91]
Hi, I don't have an issue to report but rather a question to ask.

For the transition type, we have 'enter', 'exit' and 'both'. If I'm using the status 'both', how do I know whether the geofence is entered or exited? 

Thanks in advance!

**Comment by johnrobertcobbold** [comment]
Not possible, although someone had worked out a fork for this I believe in a previous issue. I would also like to be able to know this.

**Comment by derek1988ec** [comment]
@johnrobertcobbold do you know which fork it is?

**Comment by andiCR** [comment]
@derek1988ec hey man, I have a version of the plugin that changed this here:
https://github.com/andiCR/cordova-plugin-geofence
It's basically a new parameter named 'handledTransition', included in the commits from May 26 and May 27. Had to hack my way thru the unmutable json class and modify the resulting string instead.

**Comment by johnrobertcobbold** [comment]
thanks @andiCR, I will also check this out

**Comment by derek1988ec** [comment]
thanks a bunch @andiCR !!! :D

**Comment by johnrobertcobbold** [comment]
@andiCR Thanks for that, I just tested it and it's working nicely (at least on iOS, not using Android for now). Just had to update one line for it to be compatible with Swift 2.0. I wrote a note in the relevant commit in your fork.
