### ISSUE TITLE
On geofence crossing, js error thrown [Error] SyntaxError: Unexpected identifier 't'. Expected ')' to end a argument list

### ISSUE THREAD

**Issue by garrettlangley** [cowbell/cordova-plugin-geofence#94]
The line at error appears to be coming from https://github.com/cowbell/cordova-plugin-geofence/blob/master/src/ios/GeofencePlugin.swift#L142

For me, the data is:
`{"_id":"56323a2c5272910412000039"}`

**Comment by garrettlangley** [comment]
anything here?

**Comment by garrettlangley** [comment]
?

**Comment by tsubik** [comment]
I couldn't reproduce that bug using data object as you had.
