### ISSUE TITLE
Android background location check

### ISSUE THREAD

**Issue by chavika** [cowbell/cordova-plugin-geofence#98]
Hi,

This looks like a great plugin,but before i continue i would like to know whether this plugin can check for a users location with pre define geofences in background and display a notification on android and IOS

Thank you,
Chavika

**Comment by tsubik** [comment]
Short answer is Yes. You can specify notification on geofence transition, but if you want to execute custom code you need to do it in native way https://github.com/cowbell/cordova-plugin-geofence#listening-for-geofence-transitions-in-native-code

**Comment by chavika** [comment]
Thank you very much for this amazing plugin.keep up the good work
